[2024-11-11T07:20:05.200+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-11T07:20:05.231+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_op_sample_1.create_save_df manual__2024-11-11T07:20:01.091176+00:00 [queued]>
[2024-11-11T07:20:05.249+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_op_sample_1.create_save_df manual__2024-11-11T07:20:01.091176+00:00 [queued]>
[2024-11-11T07:20:05.249+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-11T07:20:05.275+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): create_save_df> on 2024-11-11 07:20:01.091176+00:00
[2024-11-11T07:20:05.290+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=55086) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-11T07:20:05.292+0000] {standard_task_runner.py:72} INFO - Started process 55095 to run task
[2024-11-11T07:20:05.293+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'python_op_sample_1', 'create_save_df', 'manual__2024-11-11T07:20:01.091176+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dag1_py_op_sample.py', '--cfg-path', '/tmp/tmpl1ws_fd8']
[2024-11-11T07:20:05.295+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask create_save_df
[2024-11-11T07:20:05.386+0000] {task_command.py:467} INFO - Running <TaskInstance: python_op_sample_1.create_save_df manual__2024-11-11T07:20:01.091176+00:00 [running]> on host b86342c5c47f
[2024-11-11T07:20:05.539+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='python_op_sample_1' AIRFLOW_CTX_TASK_ID='create_save_df' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T07:20:01.091176+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-11T07:20:01.091176+00:00'
[2024-11-11T07:20:05.541+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-11T07:20:05.542+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-11T07:20:05.542+0000] {logging_mixin.py:190} INFO - Current task name:create_save_df state:running start_date:2024-11-11 07:20:05.231975+00:00
[2024-11-11T07:20:05.543+0000] {logging_mixin.py:190} INFO - Dag name:python_op_sample_1 and current dag run status:running
[2024-11-11T07:20:05.543+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-11T07:20:05.545+0000] {logging_mixin.py:190} INFO - Starting with the first task in my Python Op Dag
[2024-11-11T07:20:05.558+0000] {logging_mixin.py:190} INFO - My first task in the Dag is finished
[2024-11-11T07:20:05.558+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-11T07:20:05.578+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-11T07:20:05.580+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=python_op_sample_1, task_id=create_save_df, run_id=manual__2024-11-11T07:20:01.091176+00:00, execution_date=20241111T072001, start_date=20241111T072005, end_date=20241111T072005
[2024-11-11T07:20:05.600+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-11T07:20:05.601+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-11T07:20:05.601+0000] {logging_mixin.py:190} INFO - Dag name:python_op_sample_1 queued_at:2024-11-11 07:20:01.158587+00:00
[2024-11-11T07:20:05.602+0000] {logging_mixin.py:190} INFO - Task hostname:b86342c5c47f operator:PythonOperator
[2024-11-11T07:20:05.631+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-11T07:20:05.684+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-11T07:20:05.689+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
